### ISSUE TITLE
[FEATURE] Unterkategorie löschen

### ISSUE THREAD

**Issue by Nyoko2** [Shirisu/autoPetiteTCGScript#23]
Ich würde gerne Unterkategorien löschen kann. Falls man mal aufräumt und die Kategorie nutzlos wird, muss man sie direkt in der Datenbank löschen <3

**Comment by Kasuna89** [comment]
XD Wollte gerade selbst deswegen einen Post aufmachen weil mir aufgefallen ist das man das nicht löschen kann 👍
