### ISSUE TITLE
[BUG] Direktlink in trade_offer

### ISSUE THREAD

**Issue by Nyoko2** [Shirisu/autoPetiteTCGScript#30]
In der Datei tcg/trade/trade_offer.php ist in Zeile 200 die URL für die Karte für das change event.

`document.querySelector('.own-card').style.backgroundImage = 'url(<?php echo HOST_URL; ?>/assets/cards/'+ own_card_carddeck_name +'/'+ own_card_carddeck_name+own_card_number +'.<?php echo TCG_CARDS_FILE_TYPE; ?>)';`

Diese wird jedoch mit dem direktlink /assets/cards/ ausgelesen - den Pfad legt man in der config fest und müsste hier angepasst werden (:

**Comment by liviascapin** [comment]
Steht da nicht bei TCG_CARDS_FOLDER DO NOT EDIT? Haha.
