### ISSUE TITLE
[BUG] Memory lädt endlos

### ISSUE THREAD

**Issue by Kasuna89** [Shirisu/autoPetiteTCGScript#35]
Ich wollte gerade das Memory Spiel nochmal ausprobieren und fand mich in einem Endlos Ladeprozess wieder. Leider kann ich nicht sagen woran es liegt. 

Gestern hatte ich noch keine Cardsets hochgeladen und ich konnte das Spiel ohne Probleme aufrufen bis ich darauf aufmerksam gemacht habe und eine "Du hast noch nicht genug Karten hochgeladen, also geht das Spiel noch nicht" Sperre eingebaut wurde :D

Hochgeladen wurden heute 3 Cardsets mit je 16 Karten. 

Wenn ich die Endlos Lade Schleife abbreche, also die Seite anhalte erhalte ich folgenden Screen: 
![memoryissue](https://user-images.githubusercontent.com/42219906/111666397-f91b3c80-8813-11eb-9507-5422acc6fe98.png)

**Comment by Shirisu** [comment]
Hmmm, ich kann den Fehler nicht reproduzieren.. taucht er immer noch auf?
Was sagt denn die Browser Fehlerkonsole?

**Comment by Kasuna89** [comment]
Hier ein paar Screenshots die gewünscht wurden.
![memoryissue2](https://user-images.githubusercontent.com/42219906/111785969-8ff00380-88bd-11eb-922c-203ce4324e5f.png)
![memoryissue3](https://user-images.githubusercontent.com/42219906/111785972-91213080-88bd-11eb-8b48-51c76a08be1c.png)
![memoryissue4](https://user-images.githubusercontent.com/42219906/111785974-91b9c700-88bd-11eb-9a79-9b1752742dd3.png)

**Comment by DevilClaire** [comment]
das problem hab ich ebenfals mit dem memory
