### ISSUE TITLE
[FEATURE] Keep Funktion

### ISSUE THREAD

**Issue by Kasuna89** [Shirisu/autoPetiteTCGScript#36]
Ich fände eine Keep Funktion für Karten die man erst später sammeln möchte und noch nicht in die Collect packen will ganz cool. Ich bin zum Beispiel jemand der nicht gerne alles gleich in die Collect schiebt wenns nur eine Karte ist :D

**Comment by Shirisu** [comment]
Ist hierfür nicht geplant und auch nicht gewollt, weil es etwas gegen den Sinn des MiniTCGs geht :)
