### ISSUE TITLE
[FEATURE] Puzzle Filler

### ISSUE THREAD

**Issue by Kasuna89** [Shirisu/autoPetiteTCGScript#37]
Ein weiterer Wunsch wäre einen extra Filler für Puzzle hochladen zu können, somit könnte man das Design für beide Filler unterschiedlich anpassen :)

**Comment by Shirisu** [comment]
Dann müsste für jede einzelne mögliche Karte eine Filler angelegt und ausgelesen werden.
Hätte ich jetzt so nicht vorgesehen einzubauen, da ich den großen Mehrwert nicht sehe.

Wenn du das aber gerne haben möchtest, dann kannst du das ja einfach selbst einmal einbauen - im Grunde einfach die normale Kartenausgabe beim Filler eintragen und dann eben `filler1`, `filler2`, ... nutzen statt dem Kartennamen ^^

**Comment by Kasuna89** [comment]
Wie bzw. wo genau würde ich das denn machen? Nicht das ich irgendwas kaputt mach :D

**Comment by Nyoko2** [comment]
Du kannst ja nichts kaputt machen, weil du ja alles wieder zurückstellen kannst.
Ich hab mir das eben kurz für WH TCG angeschaut und hab 2 Zeilen hinzugefügt überall da, wo Decks ausgegeben werden (zb cards_collect.php).
Einfach den Pfad für die Puzzle_Filler erstellen, abfragen ob es ein puzzle ist, wenn ja, dann den anderen Pfad wählen. Sind 2 Zeilen insgesamt ^^

Ich habs jetzt bei WH zum Testen eingebaut, so würde das Ergebnis denn aussehen:
![fillerpuzzles](https://user-images.githubusercontent.com/77638931/111871948-0ad41f80-898d-11eb-9c8e-081bca5c06e4.JPG)

**Comment by Kasuna89** [comment]
Aaah ok dann werd ich mir das mal genauer angucken :) Danke dir ^^
