### ISSUE TITLE
[FEATURE] Bildquelle

### ISSUE THREAD

**Issue by DevilClaire** [Shirisu/autoPetiteTCGScript#39]
Ich wollte mal fragen ob es möglich wäre eine Default bei der Bildquelle angabe zu machen.

Den jede angabe wird als 1, 2, 3 usw... angeben via Link.

Und da ich viele Bilder direkt selbst Screen und es dafür so gesehen auch keine Quelle gibt. Das eben wenn ich keine Eintrage eine Default ansicht erscheint.

z.B. Screencaps by DeckMaker oder sowas.

**Comment by Shirisu** [comment]
Mmmh, das ist im aktuellen System so nicht geplant - jedoch wäre das an sich ja schon der default, wenn man nichts angibt? :D

**Comment by Kasuna89** [comment]
Ich glaube es geht eher darum das man auwählen kann z.B. Bildquelle: Ingame oder Selbsterstellt oder ka was, das man evtl. nen eigenen Text eingeben kann wenns kein Link ist

**Comment by DevilClaire** [comment]
genau das was kasu denkt mein ich xD

**Comment by Nyoko2** [comment]
Theoretisch gesehen, kannst du das doch ändern, wenn kein Copyright angegeben wurde (der ja ein Link ist), dann kommt ein statischer Wert hin. Dann hättest du in allen Fällen, wo du keine explizite Bildquelle hast, den statischen Wert als Copyright drinne (wenn es halt immer der gleiche ist wie Selbsterstellt)

**Comment by Kasuna89** [comment]
Ich möchte hier gerne auch anmerken das die Bilderquellen ein Zeichen Minimum haben. Wäre super wenn man das vielleicht aufheben könnte. Ich hab nicht mehr als 5 Links hinbekommen ^^'

**Comment by Nyoko2** [comment]
> Ich möchte hier gerne auch anmerken das die Bilderquellen ein Zeichen Minimum haben. Wäre super wenn man das vielleicht aufheben könnte. Ich hab nicht mehr als 5 Links hinbekommen ^^'

Meinst du nicht eher ein maximum?

**Comment by Kasuna89** [comment]
Jap, sorry ^^'

**Comment by Shirisu** [comment]
Ah, das ist auch fälschlicherweise drin :D 
Kommt mit dem nächsten Release raus.
