### ISSUE TITLE
[FEATURE] Gezielte Karten verteilen

### ISSUE THREAD

**Issue by Kasuna89** [Shirisu/autoPetiteTCGScript#66]
Ich würde mir wünschen, dass man nicht nur Random sondern auch gezielte Karten vergeben könnte :)

**Comment by Shirisu** [comment]
Das ist im Grundscript nicht vorgesehen, kann aber gerne selbst hinzugefügt werden ^^

**Comment by Kasuna89** [comment]
Alright, danke ^^
