### ISSUE TITLE
[BUG] Everything is T?

### ISSUE THREAD

**Issue by ShikkieT** [Shirisu/autoPetiteTCGScript#71]
I just downloaded the 2.0.0 version, edited the two inc files and uploaded them to my directory. Imported the tables and made the admin account just fine. However, when I go to the every single page logged out and logged in, and in the admin section, EVERYTHING show as "T". I haven't changed any coding in any way, so im not sure what's happening here. Screen shot added!

![script](https://user-images.githubusercontent.com/81897873/113500920-cea5d080-94ef-11eb-8da0-290a598d7e53.png)

**Comment by Shirisu** [comment]
Which PHP version do you use?
You need at least version 7.2 or higher

**Comment by ShikkieT** [comment]
I'm using 7.4.

**Comment by Shirisu** [comment]
Hmmm, that's strange.
Can you test this on your local computer with xampp (for example)?

**Comment by ShikkieT** [comment]
It seems to have fixed itself, as it looks normal now. That was really strange.
![script2](https://user-images.githubusercontent.com/81897873/113520924-2f6ef080-9564-11eb-8a2c-f781bfdfad3c.png)

**Comment by Shirisu** [comment]
Very strange! :D
But good that it works now - then I will close this issue.
