### ISSUE TITLE
[BUG] Ausblenden von Lucky Games

### ISSUE THREAD

**Issue by Kasuna89** [Shirisu/autoPetiteTCGScript#72]
Es wäre cool wenn man die Lucky Kategorie Games entweder selbst aktivieren oder deaktivieren könnte oder was auf jedenfall super wäre, falls in der Kategorie keine Cardsets aktiv sind, dass das Lucky Game ansich ausgeblendet wird, sonst hat man nur eine leere Seite.

**Comment by Shirisu** [comment]
Die Kategorien werden nur angezeigt, wenn mind 1 Carddeck in der Kategorie einsortiert ist. Aber ich seh gerade, dass dort noch die Abfrage fehlt, ob das auch aktiv ist. Fix kommt gleich ^^
