### ISSUE TITLE
[FEATURE]WYSIWYG Editor

### ISSUE THREAD

**Issue by Kasuna89** [Shirisu/autoPetiteTCGScript#74]
Es wäre echt super wenn man einen WYSIWYG Editor in die News bauen könnte bzw. die üblichen Befehle wie <b> und <i> mit einbinden könnte :)

**Comment by Nyoko2** [comment]
Also,
für einen WYSIWYG Editor musst du einfach einen für den Framework und Theme raussuchen und einbinden, wahrscheinlich dann für Bootstrap. ich würde dringend davon abraten, einen als default einzubauen, da es meist überflüssig ist und viel zu viel Probleme verursachen kann.

Wenn du zb. nur fettgedruckt, unterstrichen, zentriert, emotes etc. einbauen möchtest, würde ich wirklich sehr BBCODES empfehlen. Das ist simpel und leicht einzubauen, ohne Probleme mit anderen libs. Und ist meiner Meinung nach vollkommen ausreichen für die meisten Zwecke.

Und Shirisu hat es bereits mehrfach erwähnt, dass TCG deckt sämtliche Grundbedürfnisse ab und ist abgeschlossen. Es werden nur noch Fehler gefixt - wenn du spezielle Sachen haben willst, musst du sie selbst einbauen, dafür ist der Code ja öffentlich zur Verfügung gestellt (: 
(Vielleicht baut sie trotzdem was davon ein, da musst du sie Fragen, aber sie hat das Projekt hier abgeschlossen und arbeitet an WS V3).

**Comment by Shirisu** [comment]
Wie Maron bereits sagte, ich baue maximal einfache BBCodes noch ein, einen extra Editor wird es nicht geben.
Aber da ich mich nun auf WS v3 konzentrieren möchte, wollte ich nur noch Bugfixes machen.

Das Grundgerüst steht und kann ja einfach erweitert werden.

**Comment by Kasuna89** [comment]
Ok x3 Danke für die Hilfe und Aufklärung.
