### ISSUE TITLE
[FEATURE] Down-Leveln

### ISSUE THREAD

**Issue by Nyoko2** [Shirisu/autoPetiteTCGScript#80]
Wird man automatisch ein Level zurückgesetzt, wenn man Karten verliert und unter die Grenze rutscht?
Für die Zukunft wäre es eventuell gut, wenn man x Karten gegen 1 random Karte eintauscht - dann wäre das erneute Leveln eher kontra produktiv :D

**Comment by Shirisu** [comment]
Ist aktuell nicht möglich - selbst wenn man Karten verlieren würde (was aktuell nicht möglich ist), so bleibt man auf seinem Level (auch wenn man laut Liste weniger Karten hat).
