### ISSUE TITLE
[FEATURE] Alle Nachrichten aufeinmal löschen

### ISSUE THREAD

**Issue by Nyoko2** [Shirisu/autoPetiteTCGScript#91]
Ich hätte gerne im Postfach ein Button mit "Alle Nachrichten löschen" (also gelesene und ungelesene) um die Systemnachrichten löschen zu können.

**Comment by Shirisu** [comment]
Also einfach einen Button für "Alle gelesenen Nachrichten löschen" und einen für "Alle Systemnachrichten löschen"?
Oder nur für Systemnachrichten? 
Bei SN egal ob gelesen/ungelesen dann ^^

**Comment by Nyoko2** [comment]
Einfahc einen für "Alle Systemnachrichten" löschen, damit die von anderen Mitgliedern nicht anegfasst werden. Dann sollen antürlich alle ungelesenen und gelesenen davon betroffen sein :)
